- name: "Rename user database"
  set_fact:
    all_users: "{{ users }}"
- name: "Filter user database for admins users"
  set_fact:
    admin_users: "{{ admin_users | default([]) + [item] }}" 
  with_items: "{{ all_users }}"
  when: "'{{ filter_by_group }}' in item.groups | default([]) | json_query('[*].name')"
- name: "Replace user database with admin_users"
  set_fact:
    users: "{{ admin_users }}"

- name: "Rename groups database"
  set_fact:
    all_groups: "{{ users_groups }}"
- name: "Filter user database for admins groups"
  set_fact:
    admin_groups: "{{ admin_groups | default([]) + [item]  }}"      
  with_items: "{{ all_groups }}"
  when: "item.name in users | json_query('[*].name') or item.name == 'datexis' or item.name == 'docker_gpu'"
- name: "Replace user database with admin_groups"
  set_fact:
    users_groups: "{{ admin_groups }}"

- name: "Rename sshkey  database"
  set_fact:
    all_sshkeys: "{{ users_ssh }}"
- name: "Filter user database for admins groups"
  set_fact:
    admin_sshkeys: "{{ admin_sshkeys | default([]) + [item]  }}"      
  with_items: "{{ all_sshkeys }}"
  when: "item.name in users | json_query('[*].name')"
- name: "Replace user database with admin_groups"
  set_fact:
    users_ssh: "{{ admin_sshkeys }}"

