---
- name: "Create groups"
  group:
    gid: "{{ item.gid|default('') }}"
    name: "{{ item.name }}"
    system: "{{ item.system|default('no') }}"
    state: present
  with_items: "{{ users_groups }}"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts)
