---
- name: "filter user db"
  include: filter_user_db.yml
  when: filter_by_group is defined

- inlcude: overwrite_create_home.yml
  when: overwrite_create_home is defined and overwrite_create_home 

- include: users_removal.yml

- include: groups_removal.yml

- include: groups.yml

- include: users.yml

- include: sudo.yml

- include: ssh.yml

- include: umask.yml
  when: users_set_umask
