- name: "overwrite create home"
  set_fact:
    overwrite_users: "{{ overwrite_users | default([]) + [{ 'name':item.name,'shell':item.shell,'home':item.home,'uid':item.uid,'group':item.group,'groups':item.groups|default([]),'comment':item.comment,'system':item.system,'createhome': true}] }}"
  with_items: "{{ users }}"
