---
- name: "Remove absent users"
  user:
    name: "{{ item.name }}"
    state: absent
    comment: "{{ item.comment|default('') }}"
    uid: "{{ item.uid }}"
    group: "{{ item.group }}"
  with_items: "{{ users_absent }}"
  when: (item.only_on_hosts is not defined and item.not_on_hosts is not defined) or (item.only_on_hosts is defined and item.not_on_hosts is defined) or (item.only_on_hosts is defined and inventory_hostname in item.only_on_hosts) or (item.not_on_hosts is defined and inventory_hostname not in item.not_on_hosts)
